### ISSUE TITLE
Merge some more REST-API and Backend tests

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/RADAR-Commons#12]
As per comment @nivemaham in #11:
> There are still few more classes we could add to commons-test that can be reusable in rest-api and mongo-db-connector e2e tests.

**Comment by nivemaham** [comment]
Solved in this [revision](https://github.com/RADAR-CNS/RADAR-Commons/commit/537b46fbb365da80dc07252f4906c9e30335867b)
