### ISSUE TITLE
Distribution: publish the package to JCenter

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-CNS/RADAR-Commons#4]
Right now, the project can only be used as a git submodule/gradle subproject. It would be nicer to publish a version to JCenter each time we do a release. That would solve dependency management automatically. See the [JCenter Gradle plugin](https://github.com/bintray/gradle-bintray-plugin) for more details.

**Comment by nivemaham** [comment]
An initial release under version 0.1 is published in bintray. 
To use the releases add maven { url 'http://dl.bintray.com/radar-cns/org.radarcns'} under repositories and use   compile group: 'org.radarcns', name: 'radar-commons', version: '0.1'. 
Integrating SNAPSHOT versions are WIP
