### ISSUE TITLE
Fail build if release cycle is not successfully processed. 

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/RADAR-Commons#9]
Travis build status should indicate FAILED if releases are performed and github or bintrayUpload are not successful.

**Comment by blootsvoets** [comment]
This is an issue with travis-ci/travis-ci#1574. We could use a `travis_terminate` command according to that issue, although that is undocumented.

**Comment by blootsvoets** [comment]
In any case, we have to go to bintray and press publish, so that will also tell us that the upload failed, right?
